// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLYCL9ZbLPmE1f-11odcxSqYdAy5nmwls',
    appId: '1:407947362845:web:fa32fd85783e1fda3ebcf4',
    messagingSenderId: '407947362845',
    projectId: 'cet165quiz',
    authDomain: 'cet165quiz.firebaseapp.com',
    storageBucket: 'cet165quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7DaaH7H9wKosDKWlgGGaj-bVgcRUbnRg',
    appId: '1:407947362845:android:877d4acf21b4c5f53ebcf4',
    messagingSenderId: '407947362845',
    projectId: 'cet165quiz',
    storageBucket: 'cet165quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlkhD55n8QhLO6vA9bRyI2jLgcFC42-3g',
    appId: '1:407947362845:ios:1d5b6bae8f87d09d3ebcf4',
    messagingSenderId: '407947362845',
    projectId: 'cet165quiz',
    storageBucket: 'cet165quiz.firebasestorage.app',
    iosBundleId: 'com.example.cet165quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlkhD55n8QhLO6vA9bRyI2jLgcFC42-3g',
    appId: '1:407947362845:ios:1d5b6bae8f87d09d3ebcf4',
    messagingSenderId: '407947362845',
    projectId: 'cet165quiz',
    storageBucket: 'cet165quiz.firebasestorage.app',
    iosBundleId: 'com.example.cet165quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLYCL9ZbLPmE1f-11odcxSqYdAy5nmwls',
    appId: '1:407947362845:web:dd3b4e2290c3095b3ebcf4',
    messagingSenderId: '407947362845',
    projectId: 'cet165quiz',
    authDomain: 'cet165quiz.firebaseapp.com',
    storageBucket: 'cet165quiz.firebasestorage.app',
  );
}
